# Generated by Django 3.2.18 on 2023-03-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='collected_amount',
            field=models.FloatField(null=True),
        ),
    ]
