# Generated by Django 3.2.18 on 2023-03-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_advertisement_collected_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='collected_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
